### ISSUE TITLE
运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果

### ISSUE THREAD

**Issue by wulispa** [PaddlePaddle/VisualDL#1235]
![图片](https://user-images.githubusercontent.com/101657716/225890469-50e67b65-8d6c-4c19-809f-9e9b411051fb.png)
生成了log文件了，然后输入visualdl --logdir ./log/graph_test/ --port 8080，然后再浏览器进入http://127.0.0.1:8080/app/graph/static_graph。没结果，如下图
![图片](https://user-images.githubusercontent.com/101657716/225890673-7acbfc90-b789-4592-837c-8742da73f2b1.png)

**Comment by rainyfly** [comment]
这个是动态图，我大概知道原因在哪，你可以在启动时候，试着加一个 --component_tabs dynamic_graph试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wulispa ***@***.***&gt;
发送时间: 2023年3月17日 19:20
收件人: PaddlePaddle/VisualDL ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235)





 

 生成了log文件了，然后输入visualdl --logdir ./log/graph_test/ --port 8080，然后再浏览器进入http://127.0.0.1:8080/app/graph/static_graph。没结果，如下图

**Comment by wulispa** [comment]
那一直加载是正常的吗

**Comment by rainyfly** [comment]
不正常，如果刷新几次都出不来肯定哪里有问题，这边会check一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wulispa ***@***.***&gt;
发送时间: 2023年3月17日 19:48
收件人: PaddlePaddle/VisualDL ***@***.***&gt;
抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235)





 
那一直加载是正常的吗

**Comment by Marieology** [comment]
same problem here!! hope to know the solution..

**Comment by wulispa** [comment]
> 不正常，如果刷新几次都出不来肯定哪里有问题，这边会check一下 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wulispa ***@***.***&gt; 发送时间: 2023年3月17日 19:48 收件人: PaddlePaddle/VisualDL ***@***.***&gt; 抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 那一直加载是正常的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

试了几次还是不行诶

**Comment by rainyfly** [comment]
要不回退一下版本到2.4.0先试试看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Marieology ***@***.***&gt;
发送时间: 2023年3月17日 19:54
收件人: PaddlePaddle/VisualDL ***@***.***&gt;
抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235)





 
same problem here!! hope to know the solution..

**Comment by rainyfly** [comment]
pip install visualdl==2.4.0 flask_babel==2.0.0&nbsp;
回退一些版本先试试，这边检查出问题了会尽快进行修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wulispa ***@***.***&gt;
发送时间: 2023年3月17日 19:56
收件人: PaddlePaddle/VisualDL ***@***.***&gt;
抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235)





  
不正常，如果刷新几次都出不来肯定哪里有问题，这边会check一下 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: wulispa @.&gt; 发送时间: 2023年3月17日 19:48 收件人: PaddlePaddle/VisualDL @.&gt; 抄送: chenjian @.&gt;, Comment @.&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 那一直加载是正常的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
试了几次还是不行诶

**Comment by wulispa** [comment]
ModuleNotFoundError: No module named 'multiprocess'

退完版本用visualdl --logdir ./log/graph_test/ --port 8080 --component_tabs dynamic_graph的时候报错了

**Comment by wulispa** [comment]
> pip install visualdl==2.4.0 flask_babel==2.0.0&nbsp; 回退一些版本先试试，这边检查出问题了会尽快进行修复 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wulispa ***@***.***&gt; 发送时间: 2023年3月17日 19:56 收件人: PaddlePaddle/VisualDL ***@***.***&gt; 抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 不正常，如果刷新几次都出不来肯定哪里有问题，这边会check一下 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: wulispa @.&gt; 发送时间: 2023年3月17日 19:48 收件人: PaddlePaddle/VisualDL @.&gt; 抄送: chenjian @.&gt;, Comment @.&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 那一直加载是正常的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 试了几次还是不行诶 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
ModuleNotFoundError: No module named 'multiprocess'

退完版本用visualdl --logdir ./log/graph_test/ --port 8080 --component_tabs dynamic_graph的时候报错了

**Comment by rainyfly** [comment]
回退版本后不需要加那个--component_tabs的选项，另外少了包的话pip install multiprocess



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wulispa ***@***.***&gt;
发送时间: 2023年3月17日 20:26
收件人: PaddlePaddle/VisualDL ***@***.***&gt;
抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235)





  
pip install visualdl==2.4.0 flask_babel==2.0.0&nbsp; 回退一些版本先试试，这边检查出问题了会尽快进行修复 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: wulispa @.&gt; 发送时间: 2023年3月17日 19:56 收件人: PaddlePaddle/VisualDL @.&gt; 抄送: chenjian @.&gt;, Comment @.&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 不正常，如果刷新几次都出不来肯定哪里有问题，这边会check一下 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: wulispa @.&gt; 发送时间: 2023年3月17日 19:48 收件人: PaddlePaddle/VisualDL @.&gt; 抄送: chenjian @.&gt;, Comment @.&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 那一直加载是正常的吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 试了几次还是不行诶 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
 ModuleNotFoundError: No module named 'multiprocess'
  
退完版本用visualdl --logdir ./log/graph_test/ --port 8080 --component_tabs dynamic_graph的时候报错了

**Comment by wulispa** [comment]
![图片](https://user-images.githubusercontent.com/101657716/225907701-90e710f6-2920-4ca5-a395-67172cb279f9.png)
现在是这样了。
![图片](https://user-images.githubusercontent.com/101657716/225907859-de3ff38a-f85b-416e-bbf5-ada818cc1983.png)
我生成路径是这样的

**Comment by rainyfly** [comment]
点击网络结构里的动态图如果可以正常显示的话里面应该有内容



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wulispa ***@***.***&gt;
发送时间: 2023年3月17日 20:44
收件人: PaddlePaddle/VisualDL ***@***.***&gt;
抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235)





 

 现在是这样了。
 
 我生成路径是这样的

**Comment by wulispa** [comment]
> 点击网络结构里的动态图如果可以正常显示的话里面应该有内容 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wulispa ***@***.***&gt; 发送时间: 2023年3月17日 20:44 收件人: PaddlePaddle/VisualDL ***@***.***&gt; 抄送: chenjian ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [PaddlePaddle/VisualDL] 运行完graph后，成功生成log文件，但进入浏览页没显示可视化模型结果 (Issue #1235) 现在是这样了。 我生成路径是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

还是一直加载诶

**Comment by rainyfly** [comment]
不好意思，我发现最后一条消息上周五邮件没发出去。你用的是什么浏览器呢，是chrome吗，如果是的话要不把你的日志文件打包发给我的邮箱，我来调试一下看看哪里的问题

**Comment by Marieology** [comment]
Hi! I appreciate your effort!

I'm using Chrome as my browser
 vdlrecords.1679141912.log
<https://drive.google.com/file/d/1-2o0R3_fyeokoum_MxsbaB-YbO0ph39_/view?usp=drive_web>

I downgraded to version 2.4.0, and now I can see the scalars, but still I
cannot see the other graphs, histograms, or ROC curves

Is there something else to install or register to use other section??

cmd : visualdl -- path/to/log/ --port 8080
[image: image.png]
[image: image.png] < More - ROC


2023년 3월 20일 (월) 오후 12:43, chenjian ***@***.***>님이 작성:

**Comment by wulispa** [comment]
> 不好意思，我发现最后一条消息上周五邮件没发出去。你用的是什么浏览器呢，是chrome吗，如果是的话要不把你的日志文件打包发给我的邮箱，我来调试一下看看哪里的问题
好的，发了

**Comment by wulispa** [comment]
好的，发过去了

**Comment by rainyfly** [comment]
![image](https://user-images.githubusercontent.com/22424850/227099120-60fc2623-0731-4664-9718-5a01f9d31322.png) @wulispa 我这里在Linux环境下是可以正常看你的日志的，我怀疑是windows下面vdl的使用有问题，这个我们之后验证看看哪里需要修复的

**Comment by rainyfly** [comment]
@Marieology Hi，Are you sure if you have logged graphs, histograms data in your log file etc. Only the data you write in the log file will be shown in the page. If data not exists, the corresponding page has no graph to show. And what data you need totally depends on yourself, i.e. use LogWriter to write data in the log file.

**Comment by wulispa** [comment]
> ![image](https://user-images.githubusercontent.com/22424850/227099120-60fc2623-0731-4664-9718-5a01f9d31322.png) @wulispa 我这里在Linux环境下是可以正常看你的日志的，我怀疑是windows下面vdl的使用有问题，这个我们之后验证看看哪里需要修复的

可以把中间那个细节截个图发给我吗，我需要用到，毕竟一时半会搞不出来

**Comment by rainyfly** [comment]
@wulispa 已经发送到你的邮箱拉

**Comment by wulispa** [comment]
@rainyfly 没收到诶，麻烦发这个415971619@qq.com，谢谢啦

**Comment by wulispa** [comment]
> @wulispa 已经发送到你的邮箱拉

@rainyfly 没收到诶，麻烦发这个[415971619@qq.com](mailto:415971619@qq.com)，谢谢啦

**Comment by rainyfly** [comment]
修复的pr https://github.com/PaddlePaddle/VisualDL/pull/1244 。 这个修复将在下一个小版本中进入，如果需要在windows下使用，可以参考这个pr中修改的文件在本地对应修改一下。具体可以安装如下操作：
import visualdl
visualdl.path
看一下visualdl的安装路径，然后找到pr中修改的文件对应修改一下即能够生效。
