### ISSUE TITLE
logging enable error message output

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#205]
The logging.h has naive implementations for the interfaces of GLOG,
but the `CHECK`s can not output error messages before exceptions.

This is annoying to users and results in many troubles.

TODO:

- output the error message

**Comment by jetfuel** [comment]
@Superjomn The LogStreamFatal constructor throws errors and there is no way to have the string(extra error message) piped into the message. I noticed that the destructor also throws the exceptions. If we remove the ```throw Error(ss.str());``` in LogStreamFatal constructor, it should be able to print out the error message. It seems the implementation was there already but not confirmed. Was there any concern on doing the throw at the destructor level?

**Comment by Superjomn** [comment]
The exception in the construction is just a temporary implementation. The exception in the destruction seems work, but it  fails to break the execution of the program at the position where `CHECK` fails, the exceptions will not be threw until the end of the block (when the destruction is called).

**Comment by jetfuel** [comment]
@Superjomn I now see the concern and reason why we switch to the implementation of throwing in the constructor. 

I now have another question. We are thinking if it is possible to change the CHECK function to something like CHECK(cond, error_msg). However, I noticed that we are using the GLOG in the debug and we are using our own CHECK Macros in the release mode. 

Is this because the GLOG doesn't throw errors? and we wish to capture the errors immediately in the release mode? And is that why we implement our own CHECK functions and can't change the way we call CHECK functions? Sorry for all the questions. We are hoping to have a better understanding of the situation and provide better solutions.

**Comment by PeterPanZH** [comment]
close outdated issue.
